[build-system]
requires = ["setuptools", "numpy", "Cython"]
build-backend = "setuptools.build_meta"

[project]
name = "infinigen"
version = "1.1.0"
requires-python = "==3.10.*"
description = "Infinite Photorealistic Worlds using Procedural Generation"
keywords = [
    "computer vision", 
    "data generation", 
    "procedural"
]
classifiers = [
    "Framework :: Blender", 
    "Programming Language :: Python :: 3"
]
dependencies = [
    "bpy",
    "einops",
    "flow_vis",
    "frozendict",
    "geomdl",
    "gin_config",
    "imageio",
    "matplotlib",
    "numpy",
    "opencv-python",
    "psutil",
    "scikit-image",
    "scikit-learn",
    "scipy",
    "submitit",
    "tqdm",
    "trimesh",
    "wandb",
    "zarr",
    "pandas",
    "landlab == 2.4.1", 
    "pycparser", 
    "pyrender"
]

[project.optional-dependencies]
dev = [
    "pytest", 
    "pytest-ordering", 
    "pytest-cov", 
    "black", 
    "ruff", 
    "tabulate" # for integration test results
]

[tool.setuptools]
packages = ["infinigen"]

[tool.pytest.ini_options]
addopts = "--cov-report xml:coverage.xml --cov infinigen --cov-fail-under 0"
testpaths = "tests"
junit_family = "xunit2"
markers = [
    "integration: marks as integration test",
    "notebooks: marks as notebook test",
    "gpu: marks as gpu test",
    "spark: marks tests which need Spark",
    "slow: marks tests as slow",
    "unit: fast offline tests",
]

[tool.ruff]
select = [
    "E", 
    "F", 
    #"B", 
    #"C901",
]
target-version = "py310"
line-length = 120 # will be reduced to 88 to match black soon

exclude = [
    "*/dependencies/"
]
ignore = [
    "E402", # we have lots of sys.path and opencv statements that must preceed imports, ignore for now
    "E501", # ignore line length for now
    "E701", # disable multi line statements until we enable black
    "F401", # unused imports are sometimes necessary for gin to work
    "E712", # some people think `if x == True` is more explicit, not going to force it
] 

[tool.ruff.per-file-ignores]
"__init__.py" = []
"infinigen/assets/*" = ["F841"] #transpiler currently creates lots of unused variables


[tool.ruff.mccabe]
max-complexity = 10